/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_am1goo_playdate4j_sdk_SoundBridge_BitCrusherBridge */

#ifndef _Included_com_am1goo_playdate4j_sdk_SoundBridge_BitCrusherBridge
#define _Included_com_am1goo_playdate4j_sdk_SoundBridge_BitCrusherBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_BitCrusherBridge
 * Method:    newBitCrusher
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024BitCrusherBridge_newBitCrusher
  (JNIEnv *, jobject);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_BitCrusherBridge
 * Method:    freeBitCrusher
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024BitCrusherBridge_freeBitCrusher
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_BitCrusherBridge
 * Method:    setAmount
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024BitCrusherBridge_setAmount
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_BitCrusherBridge
 * Method:    setAmountModulator
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024BitCrusherBridge_setAmountModulator
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_BitCrusherBridge
 * Method:    getAmountModulator
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024BitCrusherBridge_getAmountModulator
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_BitCrusherBridge
 * Method:    setUndersampling
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024BitCrusherBridge_setUndersampling
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_BitCrusherBridge
 * Method:    setUndersampleModulator
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024BitCrusherBridge_setUndersampleModulator
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_BitCrusherBridge
 * Method:    getUndersampleModulator
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024BitCrusherBridge_getUndersampleModulator
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
