/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_am1goo_playdate4j_sdk_SoundBridge_SequenceTrackBridge */

#ifndef _Included_com_am1goo_playdate4j_sdk_SoundBridge_SequenceTrackBridge
#define _Included_com_am1goo_playdate4j_sdk_SoundBridge_SequenceTrackBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SequenceTrackBridge
 * Method:    newTrack
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SequenceTrackBridge_newTrack
  (JNIEnv *, jobject);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SequenceTrackBridge
 * Method:    freeTrack
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SequenceTrackBridge_freeTrack
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SequenceTrackBridge
 * Method:    setInstrument
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SequenceTrackBridge_setInstrument
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SequenceTrackBridge
 * Method:    getInstrument
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SequenceTrackBridge_getInstrument
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SequenceTrackBridge
 * Method:    addNoteEvent
 * Signature: (JJJFF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SequenceTrackBridge_addNoteEvent
  (JNIEnv *, jobject, jlong, jlong, jlong, jfloat, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SequenceTrackBridge
 * Method:    removeNoteEvent
 * Signature: (JJF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SequenceTrackBridge_removeNoteEvent
  (JNIEnv *, jobject, jlong, jlong, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SequenceTrackBridge
 * Method:    clearNotes
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SequenceTrackBridge_clearNotes
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SequenceTrackBridge
 * Method:    getLength
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SequenceTrackBridge_getLength
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SequenceTrackBridge
 * Method:    getIndexForStep
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SequenceTrackBridge_getIndexForStep
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SequenceTrackBridge
 * Method:    getNoteAtIndex
 * Signature: (JILcom/am1goo/playdate4j/sdk/SoundBridge/Note;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SequenceTrackBridge_getNoteAtIndex
  (JNIEnv *, jobject, jlong, jint, jobject);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SequenceTrackBridge
 * Method:    getControlSignalCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SequenceTrackBridge_getControlSignalCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SequenceTrackBridge
 * Method:    getControlSignal
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SequenceTrackBridge_getControlSignal
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SequenceTrackBridge
 * Method:    getSignalForController
 * Signature: (JIZ)J
 */
JNIEXPORT jlong JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SequenceTrackBridge_getSignalForController
  (JNIEnv *, jobject, jlong, jint, jboolean);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SequenceTrackBridge
 * Method:    clearControlEvents
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SequenceTrackBridge_clearControlEvents
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SequenceTrackBridge
 * Method:    activeVoiceCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SequenceTrackBridge_activeVoiceCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SequenceTrackBridge
 * Method:    getPolyphony
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SequenceTrackBridge_getPolyphony
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SequenceTrackBridge
 * Method:    setMuted
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SequenceTrackBridge_setMuted
  (JNIEnv *, jobject, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
