/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_am1goo_playdate4j_sdk_SoundBridge_DelayLineTapBridge */

#ifndef _Included_com_am1goo_playdate4j_sdk_SoundBridge_DelayLineTapBridge
#define _Included_com_am1goo_playdate4j_sdk_SoundBridge_DelayLineTapBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_DelayLineTapBridge
 * Method:    freeTap
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024DelayLineTapBridge_freeTap
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_DelayLineTapBridge
 * Method:    setTapDelay
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024DelayLineTapBridge_setTapDelay
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_DelayLineTapBridge
 * Method:    setTapDelayModulator
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024DelayLineTapBridge_setTapDelayModulator
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_DelayLineTapBridge
 * Method:    getTapDelayModulator
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024DelayLineTapBridge_getTapDelayModulator
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_DelayLineTapBridge
 * Method:    setTapChannelsFlipped
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024DelayLineTapBridge_setTapChannelsFlipped
  (JNIEnv *, jobject, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
