/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_am1goo_playdate4j_sdk_SoundBridge_ControlSignalBridge */

#ifndef _Included_com_am1goo_playdate4j_sdk_SoundBridge_ControlSignalBridge
#define _Included_com_am1goo_playdate4j_sdk_SoundBridge_ControlSignalBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_ControlSignalBridge
 * Method:    newSignal
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024ControlSignalBridge_newSignal
  (JNIEnv *, jobject);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_ControlSignalBridge
 * Method:    freeSignal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024ControlSignalBridge_freeSignal
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_ControlSignalBridge
 * Method:    clearEvents
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024ControlSignalBridge_clearEvents
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_ControlSignalBridge
 * Method:    addEvent
 * Signature: (JIFI)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024ControlSignalBridge_addEvent
  (JNIEnv *, jobject, jlong, jint, jfloat, jint);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_ControlSignalBridge
 * Method:    removeEvent
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024ControlSignalBridge_removeEvent
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_ControlSignalBridge
 * Method:    getMIDIControllerNumber
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024ControlSignalBridge_getMIDIControllerNumber
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
