/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_am1goo_playdate4j_sdk_SoundBridge_SamplePlayerBridge */

#ifndef _Included_com_am1goo_playdate4j_sdk_SoundBridge_SamplePlayerBridge
#define _Included_com_am1goo_playdate4j_sdk_SoundBridge_SamplePlayerBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SamplePlayerBridge
 * Method:    newPlayer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SamplePlayerBridge_newPlayer
  (JNIEnv *, jobject);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SamplePlayerBridge
 * Method:    freePlayer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SamplePlayerBridge_freePlayer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SamplePlayerBridge
 * Method:    getLength
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SamplePlayerBridge_getLength
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SamplePlayerBridge
 * Method:    isPlaying
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SamplePlayerBridge_isPlaying
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SamplePlayerBridge
 * Method:    play
 * Signature: (JIF)Z
 */
JNIEXPORT jboolean JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SamplePlayerBridge_play
  (JNIEnv *, jobject, jlong, jint, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SamplePlayerBridge
 * Method:    stop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SamplePlayerBridge_stop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SamplePlayerBridge
 * Method:    setOffset
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SamplePlayerBridge_setOffset
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SamplePlayerBridge
 * Method:    getOffset
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SamplePlayerBridge_getOffset
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SamplePlayerBridge
 * Method:    setRate
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SamplePlayerBridge_setRate
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SamplePlayerBridge
 * Method:    getRate
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SamplePlayerBridge_getRate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SamplePlayerBridge
 * Method:    setPlayRange
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SamplePlayerBridge_setPlayRange
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SamplePlayerBridge
 * Method:    setPaused
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SamplePlayerBridge_setPaused
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SamplePlayerBridge
 * Method:    setSample
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SamplePlayerBridge_setSample
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SamplePlayerBridge
 * Method:    setVolume
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SamplePlayerBridge_setVolume
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SamplePlayerBridge
 * Method:    getVolume
 * Signature: (JLcom/am1goo/playdate4j/sdk/SoundBridge/StereoVolume;)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SamplePlayerBridge_getVolume
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
