/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_am1goo_playdate4j_sdk_DisplayBridge */

#ifndef _Included_com_am1goo_playdate4j_sdk_DisplayBridge
#define _Included_com_am1goo_playdate4j_sdk_DisplayBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_am1goo_playdate4j_sdk_DisplayBridge
 * Method:    setRefreshRate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_DisplayBridge_setRefreshRate
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
