/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_am1goo_playdate4j_sdk_SoundBridge_OnePoleFilterBridge */

#ifndef _Included_com_am1goo_playdate4j_sdk_SoundBridge_OnePoleFilterBridge
#define _Included_com_am1goo_playdate4j_sdk_SoundBridge_OnePoleFilterBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_OnePoleFilterBridge
 * Method:    newFilter
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024OnePoleFilterBridge_newFilter
  (JNIEnv *, jobject);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_OnePoleFilterBridge
 * Method:    freeFilter
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024OnePoleFilterBridge_freeFilter
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_OnePoleFilterBridge
 * Method:    setParameter
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024OnePoleFilterBridge_setParameter
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_OnePoleFilterBridge
 * Method:    setParameterModulator
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024OnePoleFilterBridge_setParameterModulator
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_OnePoleFilterBridge
 * Method:    getParameterModulator
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024OnePoleFilterBridge_getParameterModulator
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
