/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_am1goo_playdate4j_sdk_ApiBridge */

#ifndef _Included_com_am1goo_playdate4j_sdk_ApiBridge
#define _Included_com_am1goo_playdate4j_sdk_ApiBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_am1goo_playdate4j_sdk_ApiBridge
 * Method:    isApiAvailable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_am1goo_playdate4j_sdk_ApiBridge_isApiAvailable
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
