/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_am1goo_playdate4j_sdk_GraphicsBridge */

#ifndef _Included_com_am1goo_playdate4j_sdk_GraphicsBridge
#define _Included_com_am1goo_playdate4j_sdk_GraphicsBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_am1goo_playdate4j_sdk_GraphicsBridge
 * Method:    getLCDColumns
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_am1goo_playdate4j_sdk_GraphicsBridge_getLCDColumns
  (JNIEnv *, jobject);

/*
 * Class:     com_am1goo_playdate4j_sdk_GraphicsBridge
 * Method:    getLCDRows
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_am1goo_playdate4j_sdk_GraphicsBridge_getLCDRows
  (JNIEnv *, jobject);

/*
 * Class:     com_am1goo_playdate4j_sdk_GraphicsBridge
 * Method:    getLCDRowSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_am1goo_playdate4j_sdk_GraphicsBridge_getLCDRowSize
  (JNIEnv *, jobject);

/*
 * Class:     com_am1goo_playdate4j_sdk_GraphicsBridge
 * Method:    clear
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_GraphicsBridge_clear
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_am1goo_playdate4j_sdk_GraphicsBridge
 * Method:    setDrawMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_GraphicsBridge_setDrawMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_am1goo_playdate4j_sdk_GraphicsBridge
 * Method:    drawText
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_GraphicsBridge_drawText
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_am1goo_playdate4j_sdk_GraphicsBridge
 * Method:    loadFont
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_am1goo_playdate4j_sdk_GraphicsBridge_loadFont
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_am1goo_playdate4j_sdk_GraphicsBridge
 * Method:    setFont
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_GraphicsBridge_setFont
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_GraphicsBridge
 * Method:    setTextTracking
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_GraphicsBridge_setTextTracking
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_am1goo_playdate4j_sdk_GraphicsBridge
 * Method:    getTextTracking
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_am1goo_playdate4j_sdk_GraphicsBridge_getTextTracking
  (JNIEnv *, jobject);

/*
 * Class:     com_am1goo_playdate4j_sdk_GraphicsBridge
 * Method:    loadBitmap
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_am1goo_playdate4j_sdk_GraphicsBridge_loadBitmap
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_am1goo_playdate4j_sdk_GraphicsBridge
 * Method:    freeBitmap
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_GraphicsBridge_freeBitmap
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
