/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_am1goo_playdate4j_sdk_GraphicsBridge */

#ifndef _Included_com_am1goo_playdate4j_sdk_GraphicsBridge
#define _Included_com_am1goo_playdate4j_sdk_GraphicsBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_am1goo_playdate4j_sdk_GraphicsBridge
 * Method:    setDrawMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_GraphicsBridge_setDrawMode
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
