/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_am1goo_playdate4j_sdk_SoundBridge_RingModulatorBridge */

#ifndef _Included_com_am1goo_playdate4j_sdk_SoundBridge_RingModulatorBridge
#define _Included_com_am1goo_playdate4j_sdk_SoundBridge_RingModulatorBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_RingModulatorBridge
 * Method:    newRingMod
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024RingModulatorBridge_newRingMod
  (JNIEnv *, jobject);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_RingModulatorBridge
 * Method:    freeRingMod
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024RingModulatorBridge_freeRingMod
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_RingModulatorBridge
 * Method:    setFrequency
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024RingModulatorBridge_setFrequency
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_RingModulatorBridge
 * Method:    setFrequencyModulator
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024RingModulatorBridge_setFrequencyModulator
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_RingModulatorBridge
 * Method:    getFrequencyModulator
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024RingModulatorBridge_getFrequencyModulator
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
