/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_am1goo_playdate4j_sdk_SoundBridge_AudioSampleBridge */

#ifndef _Included_com_am1goo_playdate4j_sdk_SoundBridge_AudioSampleBridge
#define _Included_com_am1goo_playdate4j_sdk_SoundBridge_AudioSampleBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_AudioSampleBridge
 * Method:    newSampleBuffer
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024AudioSampleBridge_newSampleBuffer
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_AudioSampleBridge
 * Method:    load
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024AudioSampleBridge_load
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_AudioSampleBridge
 * Method:    loadIntoSample
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024AudioSampleBridge_loadIntoSample
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_AudioSampleBridge
 * Method:    freeSample
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024AudioSampleBridge_freeSample
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_AudioSampleBridge
 * Method:    getLength
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024AudioSampleBridge_getLength
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
