/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_am1goo_playdate4j_sdk_SpriteBridge */

#ifndef _Included_com_am1goo_playdate4j_sdk_SpriteBridge
#define _Included_com_am1goo_playdate4j_sdk_SpriteBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    newSprite
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_newSprite
  (JNIEnv *, jobject);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    copy
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_copy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    freeSprite
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_freeSprite
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    setBounds
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_setBounds
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    getBounds
 * Signature: (JLcom/am1goo/playdate4j/sdk/SpriteBridge/PDRect;)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_getBounds
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    moveTo
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_moveTo
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    moveBy
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_moveBy
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    getPosition
 * Signature: (JLcom/am1goo/playdate4j/sdk/SpriteBridge/PDXY;)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_getPosition
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    setCenter
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_setCenter
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    getCenter
 * Signature: (JLcom/am1goo/playdate4j/sdk/SpriteBridge/PDXY;)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_getCenter
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    setImage
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_setImage
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    getImage
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_getImage
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    setSize
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_setSize
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    setZIndex
 * Signature: (JS)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_setZIndex
  (JNIEnv *, jobject, jlong, jshort);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    getZIndex
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_getZIndex
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    setTag
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_setTag
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    getTag
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_getTag
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    setDrawMode
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_setDrawMode
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    setImageFlip
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_setImageFlip
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    getImageFlip
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_getImageFlip
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    setStencil
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_setStencil
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    setStencilImage
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_setStencilImage
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    clearStencil
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_clearStencil
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    setClipRect
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_setClipRect
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    clearClipRect
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_clearClipRect
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    setClipRectsInRange
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_setClipRectsInRange
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    clearClipRectsInRange
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_clearClipRectsInRange
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    setUpdatesEnabled
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_setUpdatesEnabled
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    updatesEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_updatesEnabled
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    setVisible
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_setVisible
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    isVisible
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_isVisible
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    setOpaque
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_setOpaque
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    setAlwaysRedraw
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_setAlwaysRedraw
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    markDirty
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_markDirty
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    addDirtyRect
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_addDirtyRect
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    setIgnoresDrawOffset
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_setIgnoresDrawOffset
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    addSprite
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_addSprite
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    removeSprite
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_removeSprite
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    removeAllSprites
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_removeAllSprites
  (JNIEnv *, jobject);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    getSpriteCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_getSpriteCount
  (JNIEnv *, jobject);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    drawSprites
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_drawSprites
  (JNIEnv *, jobject);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    updateAndDrawSprites
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_updateAndDrawSprites
  (JNIEnv *, jobject);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    resetCollisionWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_resetCollisionWorld
  (JNIEnv *, jobject);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    setCollisionsEnabled
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_setCollisionsEnabled
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    collisionsEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_collisionsEnabled
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    setCollideRect
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_setCollideRect
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    getCollideRect
 * Signature: (JLcom/am1goo/playdate4j/sdk/SpriteBridge/PDRect;)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_getCollideRect
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    clearCollideRect
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_clearCollideRect
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    checkCollisions
 * Signature: (JFF[Lcom/am1goo/playdate4j/sdk/SpriteBridge/SpriteCollisionInfo;ILcom/am1goo/playdate4j/sdk/SpriteBridge/SpriteActualInfo;)I
 */
JNIEXPORT jint JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_checkCollisions
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jobjectArray, jint, jobject);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    moveWithCollisions
 * Signature: (JFF[Lcom/am1goo/playdate4j/sdk/SpriteBridge/SpriteCollisionInfo;ILcom/am1goo/playdate4j/sdk/SpriteBridge/SpriteActualInfo;)I
 */
JNIEXPORT jint JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_moveWithCollisions
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jobjectArray, jint, jobject);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    querySpritesAtPoint
 * Signature: (FF[JI)I
 */
JNIEXPORT jint JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_querySpritesAtPoint
  (JNIEnv *, jobject, jfloat, jfloat, jlongArray, jint);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    querySpritesInRect
 * Signature: (FFFF[JI)I
 */
JNIEXPORT jint JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_querySpritesInRect
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jlongArray, jint);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    querySpritesAlongLine
 * Signature: (FFFF[JI)I
 */
JNIEXPORT jint JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_querySpritesAlongLine
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jlongArray, jint);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    overlappingSprites
 * Signature: (J[JI)I
 */
JNIEXPORT jint JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_overlappingSprites
  (JNIEnv *, jobject, jlong, jlongArray, jint);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    allOverlappingSprites
 * Signature: ([JI)I
 */
JNIEXPORT jint JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_allOverlappingSprites
  (JNIEnv *, jobject, jlongArray, jint);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    querySpriteInfoAlongLine
 * Signature: (FFFF[Lcom/am1goo/playdate4j/sdk/SpriteBridge/SpriteQueryInfo;I)I
 */
JNIEXPORT jint JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_querySpriteInfoAlongLine
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
