/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_am1goo_playdate4j_sdk_FilesystemBridge */

#ifndef _Included_com_am1goo_playdate4j_sdk_FilesystemBridge
#define _Included_com_am1goo_playdate4j_sdk_FilesystemBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_am1goo_playdate4j_sdk_FilesystemBridge
 * Method:    getError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_am1goo_playdate4j_sdk_FilesystemBridge_getError
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
