/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_am1goo_playdate4j_sdk_SoundBridge_PDSynthLFOBridge */

#ifndef _Included_com_am1goo_playdate4j_sdk_SoundBridge_PDSynthLFOBridge
#define _Included_com_am1goo_playdate4j_sdk_SoundBridge_PDSynthLFOBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthLFOBridge
 * Method:    newLFO
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthLFOBridge_newLFO
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthLFOBridge
 * Method:    freeLFO
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthLFOBridge_freeLFO
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthLFOBridge
 * Method:    setType
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthLFOBridge_setType
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthLFOBridge
 * Method:    setRate
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthLFOBridge_setRate
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthLFOBridge
 * Method:    setPhase
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthLFOBridge_setPhase
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthLFOBridge
 * Method:    setStartPhase
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthLFOBridge_setStartPhase
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthLFOBridge
 * Method:    setCenter
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthLFOBridge_setCenter
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthLFOBridge
 * Method:    setDepth
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthLFOBridge_setDepth
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthLFOBridge
 * Method:    setArpeggiation
 * Signature: (JI[F)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthLFOBridge_setArpeggiation
  (JNIEnv *, jobject, jlong, jint, jfloatArray);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthLFOBridge
 * Method:    setDelay
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthLFOBridge_setDelay
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthLFOBridge
 * Method:    setRetrigger
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthLFOBridge_setRetrigger
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthLFOBridge
 * Method:    getValue
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthLFOBridge_getValue
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthLFOBridge
 * Method:    setGlobal
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthLFOBridge_setGlobal
  (JNIEnv *, jobject, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
