/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_am1goo_playdate4j_sdk_SoundBridge_FilePlayerBridge */

#ifndef _Included_com_am1goo_playdate4j_sdk_SoundBridge_FilePlayerBridge
#define _Included_com_am1goo_playdate4j_sdk_SoundBridge_FilePlayerBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_FilePlayerBridge
 * Method:    newPlayer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024FilePlayerBridge_newPlayer
  (JNIEnv *, jobject);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_FilePlayerBridge
 * Method:    loadIntoPlayer
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024FilePlayerBridge_loadIntoPlayer
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_FilePlayerBridge
 * Method:    freePlayer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024FilePlayerBridge_freePlayer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_FilePlayerBridge
 * Method:    pause
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024FilePlayerBridge_pause
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_FilePlayerBridge
 * Method:    play
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024FilePlayerBridge_play
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_FilePlayerBridge
 * Method:    isPlaying
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024FilePlayerBridge_isPlaying
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_FilePlayerBridge
 * Method:    setBufferLength
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024FilePlayerBridge_setBufferLength
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_FilePlayerBridge
 * Method:    getLength
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024FilePlayerBridge_getLength
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
