/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_am1goo_playdate4j_sdk_SpriteBridge */

#ifndef _Included_com_am1goo_playdate4j_sdk_SpriteBridge
#define _Included_com_am1goo_playdate4j_sdk_SpriteBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    newSprite
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_newSprite
  (JNIEnv *, jobject);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    copy
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_copy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    freeSprite
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_freeSprite
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    moveTo
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_moveTo
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    moveBy
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_moveBy
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    getPosition
 * Signature: (JLcom/am1goo/playdate4j/sdk/SpriteBridge/PDXY;)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_getPosition
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    setImage
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_setImage
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    setTag
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_setTag
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    getTag
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_getTag
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    setDrawMode
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_setDrawMode
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    setImageFlip
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_setImageFlip
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    getImageFlip
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_getImageFlip
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    setUpdatesEnabled
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_setUpdatesEnabled
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    updatesEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_updatesEnabled
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    setVisible
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_setVisible
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    isVisible
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_isVisible
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    addSprite
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_addSprite
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    removeSprite
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_removeSprite
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    removeAllSprites
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_removeAllSprites
  (JNIEnv *, jobject);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    getSpriteCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_getSpriteCount
  (JNIEnv *, jobject);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    drawSprites
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_drawSprites
  (JNIEnv *, jobject);

/*
 * Class:     com_am1goo_playdate4j_sdk_SpriteBridge
 * Method:    updateAndDrawSprites
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SpriteBridge_updateAndDrawSprites
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
