/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_am1goo_playdate4j_sdk_SoundBridge_TwoPoleFilterBridge */

#ifndef _Included_com_am1goo_playdate4j_sdk_SoundBridge_TwoPoleFilterBridge
#define _Included_com_am1goo_playdate4j_sdk_SoundBridge_TwoPoleFilterBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_TwoPoleFilterBridge
 * Method:    newFilter
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024TwoPoleFilterBridge_newFilter
  (JNIEnv *, jobject);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_TwoPoleFilterBridge
 * Method:    freeFilter
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024TwoPoleFilterBridge_freeFilter
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_TwoPoleFilterBridge
 * Method:    setType
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024TwoPoleFilterBridge_setType
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_TwoPoleFilterBridge
 * Method:    setFrequency
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024TwoPoleFilterBridge_setFrequency
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_TwoPoleFilterBridge
 * Method:    setFrequencyModulator
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024TwoPoleFilterBridge_setFrequencyModulator
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_TwoPoleFilterBridge
 * Method:    getFrequencyModulator
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024TwoPoleFilterBridge_getFrequencyModulator
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_TwoPoleFilterBridge
 * Method:    setGain
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024TwoPoleFilterBridge_setGain
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_TwoPoleFilterBridge
 * Method:    setResonance
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024TwoPoleFilterBridge_setResonance
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_TwoPoleFilterBridge
 * Method:    setResonanceModulator
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024TwoPoleFilterBridge_setResonanceModulator
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_TwoPoleFilterBridge
 * Method:    getResonanceModulator
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024TwoPoleFilterBridge_getResonanceModulator
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
