/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_am1goo_playdate4j_sdk_SoundBridge_SoundSequenceBridge */

#ifndef _Included_com_am1goo_playdate4j_sdk_SoundBridge_SoundSequenceBridge
#define _Included_com_am1goo_playdate4j_sdk_SoundBridge_SoundSequenceBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SoundSequenceBridge
 * Method:    newSequence
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SoundSequenceBridge_newSequence
  (JNIEnv *, jobject);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SoundSequenceBridge
 * Method:    freeSequence
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SoundSequenceBridge_freeSequence
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SoundSequenceBridge
 * Method:    loadMIDIFile
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SoundSequenceBridge_loadMIDIFile
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SoundSequenceBridge
 * Method:    play
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SoundSequenceBridge_play
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SoundSequenceBridge
 * Method:    stop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SoundSequenceBridge_stop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SoundSequenceBridge
 * Method:    isPlaying
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SoundSequenceBridge_isPlaying
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SoundSequenceBridge
 * Method:    getTime
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SoundSequenceBridge_getTime
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SoundSequenceBridge
 * Method:    setTime
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SoundSequenceBridge_setTime
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SoundSequenceBridge
 * Method:    setLoops
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SoundSequenceBridge_setLoops
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SoundSequenceBridge
 * Method:    getTempo
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SoundSequenceBridge_getTempo
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SoundSequenceBridge
 * Method:    setTempo
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SoundSequenceBridge_setTempo
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SoundSequenceBridge
 * Method:    getLength
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SoundSequenceBridge_getLength
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SoundSequenceBridge
 * Method:    getTrackCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SoundSequenceBridge_getTrackCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SoundSequenceBridge
 * Method:    addTrack
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SoundSequenceBridge_addTrack
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SoundSequenceBridge
 * Method:    getTrackAtIndex
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SoundSequenceBridge_getTrackAtIndex
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SoundSequenceBridge
 * Method:    setTrackAtIndex
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SoundSequenceBridge_setTrackAtIndex
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SoundSequenceBridge
 * Method:    allNotesOff
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SoundSequenceBridge_allNotesOff
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SoundSequenceBridge
 * Method:    getCurrentStep
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SoundSequenceBridge_getCurrentStep
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_SoundSequenceBridge
 * Method:    setCurrentStep
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024SoundSequenceBridge_setCurrentStep
  (JNIEnv *, jobject, jlong, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
