/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_am1goo_playdate4j_sdk_SoundBridge_DelayLineBridge */

#ifndef _Included_com_am1goo_playdate4j_sdk_SoundBridge_DelayLineBridge
#define _Included_com_am1goo_playdate4j_sdk_SoundBridge_DelayLineBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_DelayLineBridge
 * Method:    newDelayLine
 * Signature: (IZ)J
 */
JNIEXPORT jlong JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024DelayLineBridge_newDelayLine
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_DelayLineBridge
 * Method:    freeDelayLine
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024DelayLineBridge_freeDelayLine
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_DelayLineBridge
 * Method:    setLength
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024DelayLineBridge_setLength
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_DelayLineBridge
 * Method:    setFeedback
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024DelayLineBridge_setFeedback
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_DelayLineBridge
 * Method:    addTap
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024DelayLineBridge_addTap
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
