/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_am1goo_playdate4j_sdk_SoundBridge_PDSynthEnvelopeBridge */

#ifndef _Included_com_am1goo_playdate4j_sdk_SoundBridge_PDSynthEnvelopeBridge
#define _Included_com_am1goo_playdate4j_sdk_SoundBridge_PDSynthEnvelopeBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthEnvelopeBridge
 * Method:    newEnvelope
 * Signature: (FFFF)J
 */
JNIEXPORT jlong JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthEnvelopeBridge_newEnvelope
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthEnvelopeBridge
 * Method:    freeEnvelope
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthEnvelopeBridge_freeEnvelope
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthEnvelopeBridge
 * Method:    setAttack
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthEnvelopeBridge_setAttack
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthEnvelopeBridge
 * Method:    setDecay
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthEnvelopeBridge_setDecay
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthEnvelopeBridge
 * Method:    setSustain
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthEnvelopeBridge_setSustain
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthEnvelopeBridge
 * Method:    setRelease
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthEnvelopeBridge_setRelease
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthEnvelopeBridge
 * Method:    setCurvature
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthEnvelopeBridge_setCurvature
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthEnvelopeBridge
 * Method:    setVelocitySensitivity
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthEnvelopeBridge_setVelocitySensitivity
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthEnvelopeBridge
 * Method:    setRateScaling
 * Signature: (JFFF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthEnvelopeBridge_setRateScaling
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthEnvelopeBridge
 * Method:    setLegato
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthEnvelopeBridge_setLegato
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthEnvelopeBridge
 * Method:    setRetrigger
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthEnvelopeBridge_setRetrigger
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthEnvelopeBridge
 * Method:    getValue
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthEnvelopeBridge_getValue
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
