/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_am1goo_playdate4j_sdk_SoundBridge_PDSynthBridge */

#ifndef _Included_com_am1goo_playdate4j_sdk_SoundBridge_PDSynthBridge
#define _Included_com_am1goo_playdate4j_sdk_SoundBridge_PDSynthBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthBridge
 * Method:    newSynth
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthBridge_newSynth
  (JNIEnv *, jobject);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthBridge
 * Method:    freeSynth
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthBridge_freeSynth
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthBridge
 * Method:    copy
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthBridge_copy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthBridge
 * Method:    setWaveform
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthBridge_setWaveform
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthBridge
 * Method:    setSample
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthBridge_setSample
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthBridge
 * Method:    setWavetable
 * Signature: (JJIII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthBridge_setWavetable
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jint);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthBridge
 * Method:    setAttackTime
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthBridge_setAttackTime
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthBridge
 * Method:    setDecayTime
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthBridge_setDecayTime
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthBridge
 * Method:    setSustainLevel
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthBridge_setSustainLevel
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthBridge
 * Method:    setReleaseTime
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthBridge_setReleaseTime
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthBridge
 * Method:    getEnvelope
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthBridge_getEnvelope
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthBridge
 * Method:    setTranspose
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthBridge_setTranspose
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthBridge
 * Method:    setFrequencyModulator
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthBridge_setFrequencyModulator
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthBridge
 * Method:    getFrequencyModulator
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthBridge_getFrequencyModulator
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthBridge
 * Method:    setAmplitudeModulator
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthBridge_setAmplitudeModulator
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthBridge
 * Method:    getAmplitudeModulator
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthBridge_getAmplitudeModulator
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthBridge
 * Method:    playNote
 * Signature: (JFFFJ)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthBridge_playNote
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthBridge
 * Method:    playMIDINote
 * Signature: (JFFFJ)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthBridge_playMIDINote
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthBridge
 * Method:    noteOff
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthBridge_noteOff
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthBridge
 * Method:    setVolume
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthBridge_setVolume
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthBridge
 * Method:    getVolume
 * Signature: (JLcom/am1goo/playdate4j/sdk/SoundBridge/StereoVolume;)V
 */
JNIEXPORT void JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthBridge_getVolume
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthBridge
 * Method:    isPlaying
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthBridge_isPlaying
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthBridge
 * Method:    getParameterCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthBridge_getParameterCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthBridge
 * Method:    setParameter
 * Signature: (JIF)Z
 */
JNIEXPORT jboolean JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthBridge_setParameter
  (JNIEnv *, jobject, jlong, jint, jfloat);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthBridge
 * Method:    setParameterModulator
 * Signature: (JIJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthBridge_setParameterModulator
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     com_am1goo_playdate4j_sdk_SoundBridge_PDSynthBridge
 * Method:    getParameterModulator
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_am1goo_playdate4j_sdk_SoundBridge_00024PDSynthBridge_getParameterModulator
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
