set(PLAYDATE_INCLUDE_DIRS "$ENV{PLAYDATE_SDK_PATH}\\C_API;$ENV{PLAYDATE_SDK_PATH}\\C_API\\pd_api")
add_compile_definitions(TARGET_EXTENSION)
message (STATUS "PLAYDATE_INCLUDE_DIRS=${PLAYDATE_INCLUDE_DIRS}")